import './globals.css';
import { Header } from './components';
import React, { ReactNode } from 'react'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang='en' className="scroll-smooth">
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
